### PR TITLE
fix Traceback : TypeError: can only concatenate str

### LINKED ISSUE #6: Traceback : TypeError: can only concatenate str
Maybe the following error report can be used...
```
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-block-ip-range.py", line 116, in <module>
    print("jail " + jail + " unsuccessful try to ban aggregated IP network: " + ip + " (result: " + result + ")")
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can only concatenate str (not "CompletedProcess") to str
```

### PR DESCRIPTION
**Pull request by pbiering**
this fixes https://github.com/WKnak/fail2ban-block-ip-range/issues/6

### CODE REVIEW

**Comment by WKnak** [comment]
Hey! please review if this pull request is still needed, since there is a conflict that seems to fix the issue!

**Comment by pbiering** [comment]
yes, looks like it is obsolete now.

**Comment by WKnak** [comment]
Thanks, I appreciate.

**Comment by pbiering** [comment]
> Thanks, I appreciate.

but code is broken now with all the other commits...have to analyse what happened...it were not my commits which broke  the whole script :-(

**Comment by pbiering** [comment]
I'm working now on an improved one...so please wait for next PR

**Pull request closed without merging**
